[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "17"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true
